modLoader   = "javafml"
loaderVersion = "[4,)"
license       = "CC-BY-SA-4.0"

[[mods]]
modId       = "privatedimension"
version     = "${version}"
displayName = "PrivateDimension"
description = "Dimension in a Bottle - プライベート次元Mod"

[[dependencies.privatedimension]]
modId        = "neoforge"
type         = "required"
versionRange = "[${neoforge_version},)"
ordering     = "NONE"
side         = "BOTH"

[[dependencies.privatedimension]]
modId        = "minecraft"
type         = "required"
versionRange = "[${mc_version},)"
ordering     = "NONE"
side         = "BOTH"
